### ISSUE TITLE
required type for headers: HttpHeaders

### ISSUE THREAD

**Issue by DiMiTriFrog** [guzba/curly#1]
I'm trying to send post request using curly, but i'm having this issue: 

```
Error: type mismatch: got <CurlPool, string, HttpHeaders, string>
but expected one of:
proc post(pool: CurlPool; url: string; headers = emptyHttpHeaders();
          body: sink string = ""; timeout: float32 = 60): Response
  first type mismatch at position: 3
  required type for headers: HttpHeaders
  but expression 'newHttpHeaders(headers, false)' is of type: HttpHeaders
3 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them
```

PIECE of CODE:

```
let bodyRequest = %*{"id": "92jdn0", "param": "go"}
let headers =  { "Content-Type": "application/json",
    "KEY":'MY_API_KEY',
    "SIGNATURE":signature,
      }

llet response = curl.post("https://MY_URL.com", newHttpHeaders(headers), $bodyRequest)

```

I'm coming from httpclient library and all was working right. but i had low latency requests, so now i want to try with curly, but I dont know how to POST request with custom headers and body (JSON).

Thanks!

**Comment by guzba** [comment]
I need to update Curly to export `webby`. If you add `webby` to your imports that'll give you the `HttpHeaders` type from https://github.com/treeform/webby/blob/master/src/webby/httpheaders.nim

I'll update Curly to do the export soon. Explaining fix here so you can get up and running asap if you want to.

**Comment by DiMiTriFrog** [comment]
So 

> I need to update Curly to export `webby`. If you add `webby` to your imports that'll give you the `HttpHeaders` type from https://github.com/treeform/webby/blob/master/src/webby/httpheaders.nim
> 
> I'll update Curly to do the export soon. Explaining fix here so you can get up and running asap if you want to.

So what should I do???

**Comment by DiMiTriFrog** [comment]
Okey I imported webby and I now my headers var is:

```
var newHeaders: HttpHeaders
newHeaders["Content-Type"] = "application/json"
newHeaders[""KEY"] = MY_API_KEY
newHeaders["SIGNATURE"] = signature
```
