### ISSUE TITLE
Full Async Support

### ISSUE THREAD

**Issue by thatrandomperson5** [guzba/curly#18]
A fully supported async version of curly would be appreciated, if it aligns with whatever values/goals you have for this project. I currently use curly as a httpclient substitute because it works better in a threaded environment and has working http 2.0 support, but it is lacking the async functionality that httpclient provides. I understand that curly is most likely not aimed to be a httpclient replacement but for people who are migrating and people who want to use async  it would be nice to have a innate async version provided within the package. (With a medium amount of effort you can create a [async wrapper](https://gist.github.com/thatrandomperson5/8709ced4ff2e6ab84193725692a7dc99#file-asynccurly-nim) although it would probably have diminished efficiency)

**Comment by guzba** [comment]
Thanks for the suggestion, however I personally will never use anything async so that will need to be someone else's work to build and maintain.

**Comment by guzba** [comment]
It may just be for an example, but note that https://gist.github.com/thatrandomperson5/8709ced4ff2e6ab84193725692a7dc99#file-tests-nim is unnecessary. You could simply use the batch API Curly already has https://github.com/guzba/curly/?tab=readme-ov-file#multiple-requests-in-parallel

**Comment by thatrandomperson5** [comment]
> It may just be for an example, but note that https://gist.github.com/thatrandomperson5/8709ced4ff2e6ab84193725692a7dc99#file-tests-nim is unnecessary. You could simply use the batch API Curly already has https://github.com/guzba/curly/?tab=readme-ov-file#multiple-requests-in-parallel

@guzba That note is important, as I am using that example code (although slightly modified) in my source code. I don’t see how the batch API fixes the problem of blocking procedures in a async environment, could you tell me what I am missing?

**Comment by guzba** [comment]
I just observed that your specific example is the same as:

```nim
import curly

let curly = newCurly()

proc main() =
  var batch: RequestBatch
  batch.get("https://example.com")
  batch.get("https://bing.com")
  batch.post("https://example.com", body = "Hello world")

  for (response, error) in curl.makeRequests(batch):
    echo response.url
    echo response.request

main()
```

If you are doing more complex async things in your real usage scenario, then a thread oriented library like curly is not going to be a great fit without some kind of async bridge. I assume that since this is just a test it is probably not a real reflection of what you're doing so don't give too much weight to this.
